### ISSUE TITLE
Explore using alpaca to create a revision 1.1 client library

### ISSUE THREAD

**Issue by mjallday** [balanced/balanced-node#20]
[Alpaca](https://github.com/pksunkara/alpaca) is a program for generating client libraries in various languages. 

This could be a great thing for Balanced since all our client libraries are essentially mirrors of the links provided by the API. 

We could test this out with the node.js implementation and if that works expand it out to other languages.

**Comment by mjallday** [comment]
@pksunkara @mahmoudimus what do you guys think of this idea? The node client seems like a good starting point for trying this out.

**Comment by pksunkara** [comment]
I actually have a test suite at https://github.com/pksunkara/alpaca/tree/testing which tests a sample API on an sample server with all client libraries. They are all passing.

So, the generated client libraries dont need any tests if you plan to keep using alpaca. Probably the only bugs you guys can make is in the `api.json`.

**Comment by pksunkara** [comment]
By the way, I initially wanted to use Balanced as the example for alpaca, but there were some inconsistencies in the API reference and after some poking around I went with Buffer.

**Comment by pksunkara** [comment]
https://github.com/pksunkara/alpaca/blob/master/examples/balanced/api.json
https://github.com/pksunkara/alpaca/blob/master/examples/balanced/doc.json

I wrote a sample `api.json` and `doc.json` for Bank Accounts api.

According to that, all four `create`, `list`, `retrieve`, `destroy` methods are in `bank_account` class of the api.

But I think, ideally, `create` and `list` methods should be in a separate class than `retrieve` and `destroy`. I leave the choice to you guys.
