### ISSUE TITLE
Create Customer

### ISSUE THREAD

**Issue by joseym** [balanced/balanced-node#24]
> package version: `1.0.5`

The [docs](https://docs.balancedpayments.com/1.1/api/customers/#create-a-customer) show this:

``` javascript
balanced.marketplace.customers.create({
  "uri": "/customers", 
  "payload": payload // payload object
});
```

however, with that approach all I get returned in my success callback is a customer with no information besides creation time.

I'm currently doing an update in the promise **after** running create to assign the customer information, much like in my example for https://github.com/balanced/balanced-node/issues/25

**Comment by matthewfl** [comment]
this is a bug in the docs.

the request should really be:

```
balanced.marketplace.customers.create(payload);
```

so that would look like

```
balanced.marketplace.customers.create({
name: "bob"
// etc
});
```

**Comment by joseym** [comment]
Confirmed that this works correctly. Are the docs on GH? I'd be willing to PR and correct.

**Comment by matthewfl** [comment]
@joseym the examples for the client are contained in the scenario folder
https://github.com/balanced/balanced-node/blob/rev1/scenarios/customer_create/request.js

these are then incorporated into the balanced docs when it is built https://github.com/balanced/balanced-docs

if you need help figuring it out you can ping me or remear or ask in irc.

**Comment by matthewfl** [comment]
this was fixed
