### ISSUE TITLE
Get customers response returns wrong data

### ISSUE THREAD

**Issue by DarrylD** [balanced/balanced-node#36]
If I use something like so

```
balanced.configure('my-api-key');

balanced.marketplace.customers.then(function(data){
     console.log(data)
     res.send(data)
})

```

I get this response: 

```
{
  "_api": {
    "base_url": "https://api.balancedpayments.com/",
    "request_args": {
      "headers": {
        "Accept": "application/vnd.balancedpayments+json; version=1.1, application/vnd.api+json",
        "User-Agent": "balanced-node/1.2.0 node-jsonapi/0.0.10 node/v0.10.26"
      },
      "auth": {
        "user": "ak-test-2F6EHR.....4hfUlf54Pcn",
        "pass": ""
      }
    },
    "routes": {
      "marketplaces": {
        "debits": {
          "method": "GET",
          "href": "/debits"
        },
        "reversals": {
          "method": "GET",
          "href": "/reversals"
        },
        "disputes": {
          "method": "GET",
          "href": "/disputes"
        },
        "customers": {
          "method": "GET",
          "href": "/customers"
        },
        "credits": {
          "method": "GET",
          "href": "/credits"
        },
        "cards": {
          "method": "GET",
          "href": "/cards"
        },
        "orders": {
          "method": "GET",
          "href": "/orders"
        },
        "card_holds": {
          "method": "GET",
          "href": "/card_holds"
        },
        "refunds": {
          "method": "GET",
          "href": "/refunds"
        },
        "owner_customer": {
          "method": "GET",
          "href": "/customers/{marketplaces.owner_customer}"
        },
        "transactions": {
          "method": "GET",
          "href": "/transactions"
        },
        "bank_accounts": {
          "method": "GET",
          "href": "/bank_accounts"
        },
        "callbacks": {
          "method": "GET",
          "href": "/callbacks"
        },
        "events": {
          "method": "GET",
          "href": "/events"
        }
      }
    },
    "cache": {
      "/marketplaces/TEST-MP4o...JnIk5": {
        "in_escrow": 45,
        "domain_url": "example.com",
        "name": "Test Marketplace",
        "links": {
          "owner_customer": "CU4o63.....TIyN"
        },
        "href": "/marketplaces/TEST-MP4o.....JnIk5",
        "created_at": "2014-06-02T23:49:40.555048Z",
        "support_email_address": "support@example.com",
        "updated_at": "2014-06-02T23:49:41.024137Z",
        "support_phone_number": "+16505551234",
        "production": false,
        "meta": {},
        "unsettled_fees": 0,
        "id": "TEST-MP4.....Ik5",
        "_type": "marketplace",
        "_load_time": "2014-06-03T04:09:01.740Z"
      }
    },
    "last_cache_clean": "2014-06-03T04:08:57.245Z",
    "cache_time_limit": 120000,
    "objects": {},
    "action_names": {},
    "marketplace": {}
  },
  "_url": "/customers",
  "_objs": {},
  "_meta": null
}
```

Any idea why?

**Comment by matthewfl** [comment]
this is the result of the way the node client represents the objects, and the way console.log prints.  if you do `console.log(data.toJSON())` you should see the expected result, or you can do `console.log(JSON.stringify(data))`

**Comment by DarrylD** [comment]
I tried both, `console.log(data.toJSON())` hangs while `console.log(JSON.stringify(data))` is just a string of the wrong data.

I'm looking to get info as mentioned in the docs:
https://docs.balancedpayments.com/1.1/api/customers/#list-all-customers

Is it something else I'm missing or should be considering?

**Comment by matthewfl** [comment]
sorry, I missed that it appears you are trying to page through the resources.
to get the first customer it would be `balanced.marketplaces.customers.get(0).then(...`

example of paging:
http://runnable.com/Uyy6HSHlBstYTlR3/balanced-node-client-simple-paging-resources-for-node-js

**Comment by mbeynon** [comment]
This triggers a question I've been meaning to ask ...

The .get(0) above appears to set the offset to 0.  How would one specify the other optional parameters, which in this case are limit that defaults to 10?

**Comment by matthewfl** [comment]
`.get(0)` will return a single item at some offset.  If you want to get more than 1 item you can use `.range(a, a+10)` which would have an offset of `a` and a limit of `10`.

**Comment by adamwong246** [comment]
@matthewfl your example is down, however a cached copy exists http://webcache.googleusercontent.com/search?q=cache:BZfWd6uYSiYJ:runnable.com/Uyy6HSHlBstYTlR3/balanced-node-client-simple-paging-resources-for-node-js+&cd=1&hl=en&ct=clnk&gl=us

But I'm also having the same issue as @DarrylD, except I'm trying to get a list of all `orders`

```
balanced.marketplace.orders.then(function(result) {console.log(result);});
```

**Comment by adamwong246** [comment]
OK, I'll leave this as a sign for anyone else passing this way. The correct  call is 

```
balanced.marketplace.orders.range(0, 20).then(function(result) {console.log(result);});
```

retrieves the 1st 20 results. If someone can point me to a more thorough documentation of the `range`  and ``get` functions, I'd appreciate it. Specifically, how does one get _all_ of a collection, without specifying a range?

**Comment by adamwong246** [comment]
Here's the answer to my previous comment

```
balanced.marketplace.orders.then(function(page) {
  page.all().then(function(result) {
    _.each(result, function(order){
      console.log(order.description);
    });
  })
});
```
